### ISSUE TITLE
Is it possible to compile on AArch64 (Jetson Nano)?

### ISSUE THREAD

**Issue by azazdeaz** [OpenVSLAM-Community/FBoW#2]
Hi There,

I'm trying to compile on a Jetson Nano (arm64)

First, I got these errors:
```bash
cmake .. && make
c++: error: unrecognized command line option ‘-msse3’
c++: error: unrecognized command line option ‘-msse4.1’
c++: error: unrecognized command line option ‘-mavx’
```
<details>
<summary>full log</summary>
<br>
<pre>
azazdeaz@jetson:/tmp/FBoW/build$ cmake ..
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /usr (found version "4.1.1") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- 
-- ----------------------------------------
--   General configuration for fbow 0.0.1
-- ----------------------------------------
-- 
-- CMAKE_MODULE_PATH = /usr/local/lib/cmake/;/usr/lib/cmake;/usr/local/lib/cmake
-- CMAKE_INSTALL_PREFIX = /usr/local
-- CMAKE_BINARY_DIR = /tmp/FBoW/build
-- 
-- OpenCV_DIR = /usr/lib/aarch64-linux-gnu/cmake/opencv4
-- OpenCV_INCLUDE_DIRS = /usr/include/opencv4
-- OpenCV_LIBS = opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio
-- 
-- Processor: aarch64
-- Build type: Release
-- Build dynamic libs: ON
-- Build utils: OFF
-- Build tests: OFF
-- Use OpenMP: TRUE
-- 
-- C compiler: /usr/bin/cc
-- C++ compiler: /usr/bin/c++
-- 
-- C++ flags (Common): -Wall -ffunction-sections -std=c++11 -fopenmp
-- C++ flags (Release): -msse3 -msse4.1 -mavx -fomit-frame-pointer -O2 -DNDEBUG -D_NDEBUG -Wall -ffunction-sections -std=c++11 -fopenmp
-- C++ flags (Debug): -msse3 -msse4.1 -mavx -g3 -DDEBUG -D_DEBUG -Wall -ffunction-sections -std=c++11 -fopenmp
-- C++ flags (Relaese+Debug): -msse3 -msse4.1 -mavx -O2 -g3 -DDEBUG -D_DEBUG -Wall -ffunction-sections -std=c++11 -fopenmp
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/FBoW/build

azazdeaz@jetson:/tmp/FBoW/build$ make
Scanning dependencies of target fbow_lib
[ 33%] Building CXX object src/CMakeFiles/fbow_lib.dir/fbow.cpp.o
c++: error: unrecognized command line option ‘-msse3’
c++: error: unrecognized command line option ‘-msse4.1’
c++: error: unrecognized command line option ‘-mavx’
src/CMakeFiles/fbow_lib.dir/build.make:62: recipe for target 'src/CMakeFiles/fbow_lib.dir/fbow.cpp.o' failed
make[2]: *** [src/CMakeFiles/fbow_lib.dir/fbow.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/fbow_lib.dir/all' failed
make[1]: *** [src/CMakeFiles/fbow_lib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
</pre>
</details>

So I turned those options off:
```bash
cmake .. -DUSE_SSE3=OFF -DUSE_SSE4=OFF -DUSE_AVX=OFF && make
/tmp/FBoW/src/fbow.h:36:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
          ^~~~~~~~~~~~~
```
<details>
<summary>full log</summary>
<br>
<pre>
azazdeaz@jetson:/tmp/FBoW/build$ cmake .. -DUSE_SSE3=OFF -DUSE_SSE4=OFF -DUSE_AVX=OFF
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /usr (found version "4.1.1") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- 
-- ----------------------------------------
--   General configuration for fbow 0.0.1
-- ----------------------------------------
-- 
-- CMAKE_MODULE_PATH = /usr/local/lib/cmake/;/usr/lib/cmake;/usr/local/lib/cmake
-- CMAKE_INSTALL_PREFIX = /usr/local
-- CMAKE_BINARY_DIR = /tmp/FBoW/build
-- 
-- OpenCV_DIR = /usr/lib/aarch64-linux-gnu/cmake/opencv4
-- OpenCV_INCLUDE_DIRS = /usr/include/opencv4
-- OpenCV_LIBS = opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio
-- 
-- Processor: aarch64
-- Build type: Release
-- Build dynamic libs: ON
-- Build utils: OFF
-- Build tests: OFF
-- Use OpenMP: TRUE
-- 
-- C compiler: /usr/bin/cc
-- C++ compiler: /usr/bin/c++
-- 
-- C++ flags (Common): -Wall -ffunction-sections -std=c++11 -fopenmp
-- C++ flags (Release): -fomit-frame-pointer -O2 -DNDEBUG -D_NDEBUG -Wall -ffunction-sections -std=c++11 -fopenmp
-- C++ flags (Debug): -g3 -DDEBUG -D_DEBUG -Wall -ffunction-sections -std=c++11 -fopenmp
-- C++ flags (Relaese+Debug): -O2 -g3 -DDEBUG -D_DEBUG -Wall -ffunction-sections -std=c++11 -fopenmp
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/FBoW/build

azazdeaz@jetson:/tmp/FBoW/build$ make
Scanning dependencies of target fbow_lib
[ 33%] Building CXX object src/CMakeFiles/fbow_lib.dir/fbow.cpp.o
In file included from /tmp/FBoW/src/fbow.cpp:27:0:
/tmp/FBoW/src/fbow.h:36:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/fbow_lib.dir/build.make:62: recipe for target 'src/CMakeFiles/fbow_lib.dir/fbow.cpp.o' failed
make[2]: *** [src/CMakeFiles/fbow_lib.dir/fbow.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/fbow_lib.dir/all' failed
make[1]: *** [src/CMakeFiles/fbow_lib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
</pre>
</details>

I tried a bunch of things that google threw at me, but they all led to more errors. So I think I'm going in the wrong direction.
If you have any suggestion, I'd really appreciate it! :heart: 
Thanks!!

**Comment by arjunskumar** [comment]
@azazdeaz Thanks, It is working.

**Comment by Durexer** [comment]
> 
hi，Can you tell me how you compiled DXSLAM on aar64? I have the same problem

**Comment by azazdeaz** [comment]
> Can you tell me how you compiled DXSLAM on aar64? 
@Durexer I didn't. You should ask in the DXSLAM repo.

**Comment by Durexer** [comment]
> > Can you tell me how you compiled DXSLAM on aar64?
> 
> @Durexer I didn't. You should ask in the DXSLAM repo.

@azazdeaz Thanks for your reply, I would like to know if you have solved this problem or compiled it on x86 platform
